name: Publish to Maven Central

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Import GPG key
        run: |
          # Create GPG directory
          mkdir -p ~/.gnupg/
          chmod 700 ~/.gnupg
          
          # Import the GPG key
          echo "${{ secrets.GPG_SIGNING_KEY }}" | base64 --decode > ~/.gnupg/private.key
          gpg --batch --import ~/.gnupg/private.key
          
          # Trust the key
          echo "trusted-key ${{ secrets.GPG_KEY_ID }}" > ~/.gnupg/gpg.conf
          
          # Verify key import
          gpg --list-secret-keys --keyid-format=long

      - name: Download OpenAPI Spec
        run: |
          mkdir -p build/tmp
          curl -o build/tmp/openapi.yaml https://raw.githubusercontent.com/ntua-unit-of-control-and-informatics/jaqpot-api/refs/heads/main/src/main/resources/openapi.yaml

      - name: Build and Publish
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
          GPG_SIGNING_PASSWORD: ${{ secrets.GPG_SIGNING_PASSWORD }}
        run: |
          ./gradlew build publishToSonatype closeSonatypeStagingRepository --info
