name: Publish to Maven Central

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Import GPG key
        run: |
          echo "${{ secrets.GPG_SIGNING_KEY }}" | base64 --decode | gpg --batch --import
          gpg --list-secret-keys --keyid-format=long

      - name: Debug OpenAPI Download
        run: |
          mkdir -p build/tmp
          # Print working directory
          pwd
          # Try direct curl download first
          curl -o build/tmp/openapi.yaml https://raw.githubusercontent.com/ntua-unit-of-control-and-informatics/jaqpot-api/refs/heads/main/src/main/resources/openapi.yaml
          # Check file exists and content
          ls -la build/tmp/
          head -n 5 build/tmp/openapi.yaml

      - name: Run Gradle Tasks
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
          GPG_SIGNING_PASSWORD: ${{ secrets.GPG_SIGNING_PASSWORD }}
        run: |
          # Print file location again
          ls -la build/tmp/
          ./gradlew openApiGenerate --info
          ./gradlew build
          ./gradlew publishToSonatype closeSonatypeStagingRepository
